name: CI

on:
  push:
    branches:
      - experiment
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
  pull_request:
    branches:
      - experiment
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
          gradle-home-cache-cleanup: true
      - run: ./gradlew assembleLawnWithQuickstepRelease
      - uses: actions/upload-artifact@v4
        with:
          name: Universal APK
          path: build/outputs/apk/lawnWithQuickstep/release/*-universal.apk
      - uses: actions/upload-artifact@v4
        with:
          name: ARM64 APK
          path: build/outputs/apk/lawnWithQuickstep/release/*-arm64.apk
      - uses: actions/upload-artifact@v4
        with:
          name: ARMv7a APK
          path: build/outputs/apk/lawnWithQuickstep/release/*-armeabi-v7a.apk
      - uses: actions/upload-artifact@v4
        with:
          name: Mapping File
          path: build/outputs/mapping/lawnWithQuickstepRelease/mapping.txt

  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - run: ./gradlew spotlessCheck
